version: '3'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    privileged: true
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    environment:
      - DOMAIN=192.168.0.3
    volumes:
      - ./ssl:/etc/rancher/ssl:ro
      - rancher-data:/var/lib/rancher
    command: ['--acme-domain', '${DOMAIN}'] # ✅ 하드코딩 대신 환경변수 사용

volumes:
  rancher-data:
    driver: local
