version: '3'

services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    privileged: true
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./ssl:/etc/rancher/ssl:ro
      - rancher-data:/var/lib/rancher

volumes:
  rancher-data:
    driver: local
